services:
  app:
    container_name: webserver
    build:
      context: .
      target: ${NODE_ENV}
      args:
        - NODE_ENV=${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - "3000:${PORT}"
      - "9229:9229"
    volumes:
      - .:/node/app
      - /node/app/node_modules
