version: "3"
services:
  app:
    container_name: webserver
    depends_on:
      - mongo
    build:
      context: .
      target: ${NODE_ENV}
      args:
        - NODE_ENV=${NODE_ENV}
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    ports:
      - "3000:${PORT}"
    volumes:
      - .:/node/app
      - /node/app/node_modules
  mongo:
    container_name: database
    image: mongo:5.0.9
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
